### ISSUE TITLE
how to install

### ISSUE THREAD

**Issue by sonoro1234** [thenumbernine/symmath-lua#1]
Perhaps github root dir should be renamed synmath somewhere in package.path but
I see require "ext" but I dont know what ext is

**Comment by thenumbernine** [comment]
Yeah, the "symmath-lua" project needs to go in a "symmath" directory.
That's my "lua-ext" project: https://github.com/thenumbernine/lua-ext --
which needs to go in a "ext" folder name.  I still haven't got a good
naming scheme set up for my github projects, as you can see.
I have a disclaimer with my "lua-ext" project to add "?/init.lua" to your
LUA_PATH to get it to work.

**Comment by sonoro1234** [comment]
thanks for quick answer.
Have tried two tests and they print html
How do I redirect tests output to webbrowser?

**Comment by thenumbernine** [comment]
Do you mean, how did I embed it in a web-browser?  For that you should
check out Emscripten: https://github.com/kripken/emscripten .  It lets you
compile any LLVM bytecode to JavaScript.  The project has a build for the
Lua interpreter specifically that you can find here:
https://kripken.github.io/lua.vm.js/lua.vm.js.html

**Comment by sonoro1234** [comment]
No, I mean that I got html printed in the console.
I did  console redirection ( > test.html) to get it in a file. Is this the normal operation?
I have also seen that I need MathJax

**Comment by thenumbernine** [comment]
Yeah that's normal. That's the default behavior for the test cases i had
included - so i could run them in the embedded web browser version.

I'm planning to change it to default to fixed-width text output. In the
mean time just comment out the lines in each test that say
"symmath.tostring = require 'symmath.ToString.MathJax" or equivalent.

**Comment by sonoro1234** [comment]
yes but output is nicer with MathJax.
And console output is sometimes as
```
<br>
geodesic
<br>
\({d^2 x^t} \over {d\tau^2}\) =
    d                                                 d                                                        d
                                         d                                                   d
                  d                                                        d
     d                                                                         d                             d
                                           d                                                        d
           d                                   d
v ----f {d x^z}\over {d\tau} {d x^x}\over {d\tau} + ----v f {d x^z}\over {d\tau} {d x^x}\over {d\tau} -    2 ----v {d x^z}\ov
er {d\tau} {d x^t}\over {d\tau} -  2   ----f {d x^z}\over {d\tau} {d x^t}\over {d\tau} + v ----f {d x^y}\over {d\tau} {d x^x}
\over {d\tau} + ----v f {d x^y}\over {d\tau} {d x^x}\over {d\tau} -    2 ----v {d x^y}\over {d\tau} {d x^t}\over {d\tau} -  2
   ----f {d x^y}\over {d\tau} {d x^t}\over {d\tau} +                     2   ----f +                     2 ----v f -      2
                                         ----v -    2                                             ----f +  2  3
       2 ----v +  3  2                     2 ----f
   dz                                                dz                                                 v f   dz
                                  v  f  dz                                                  dy
                 dy                                                 v f   dy                                               v
 f  dy                                               {d x^x}\over {d\tau}  v  dx     {d x^x}\over {d\tau}   dx       2 v f  {
d x^x}\over {d\tau} {d x^t}\over {d\tau}  dx     2 v  f {d x^x}\over {d\tau} {d x^t}\over {d\tau}  dx     v  f  {d x^t}\over
{d\tau}   dx     v  f  {d x^t}\over {d\tau}   dx
<br>
```

**Comment by thenumbernine** [comment]
Aha, looks like the html hardcoding is a deeper problem than I thought in
my last email.  With that said, most my tests aren't going to be able to
switch away from html format so easily.  Sorry about that.

**Comment by sonoro1234** [comment]
You are working for free so please dont feel sorry.
I would only love to have some more docs and simpler tests.
I was trying to do symbolic calculus with complex rational polynomials (for a work on audio filters) but I dont know how to do that.
Thanks for your work

**Comment by thenumbernine** [comment]
I haven't got a good polynomial factoring algorithm in my symmath project
anyways.  Check out some of the more tried and true ones out there, like
Maxima.

**Comment by sonoro1234** [comment]
Yes but it is Lisp.
I wish your project could grow to make a Maxima like program (38 developers now) but in Lua.
Lua is so good language that there are a lot of one-developer projects: gsl-shell, scilua,...( I do have some of them also, althought smaller than yours) but perhaps this is the cause of being a somehow special comunity with a limit for growing.
Thanks alot for your attention.
victor bombi

**Comment by sonoro1234** [comment]
BTW: I do have a quite naif (I am just a musician) lib for polynomials and filters in https://github.com/sonoro1234/Lua2SC/tree/master/lua2SC/lua/num
It allows real, complex, polynomial and rational polynomial variables (the two last almost allow symbolic calculus) with the help of metatables
