### ISSUE TITLE
How install symmath-lua?

### ISSUE THREAD

**Issue by Bissiatti** [thenumbernine/symmath-lua#10]
How I can Install this lib on my local pc? I use luajit of [ulua](https://ulua.io/). When I download the symmath-lua, extract on my global lua libary storage and run an lua code with just this libary: "local symmath = require 'symmath'", this error occurs:

C:/lua/pkg\1_0_beta10/init.lua:834: module 'symmath' not found
        no field package.preload['symmath']
        no file 'C:/lua/symmath/init.lua'
        no file 'C:/lua/symmath.lua'
        no file 'C:/lua/luajit/2_1_head20151128/Windows/x86/symmath/init.lua'
        no file 'C:/lua/luajit/2_1_head20151128/Windows/x86/symmath.lua'
        no file 'C:/lua/symmath.dll'
        no file 'C:/lua/loadall.dll'
        no file 'C:/lua/symmath\Windows\x86\-symmath.dll'
        no file 'C:/lua/loadall.dll'
stack traceback:
        [C]: in function 'error'
        C:/lua/pkg\1_0_beta10/init.lua:834: in function 'findinit'
        C:/lua/pkg\1_0_beta10/init.lua:852: in function <C:/lua/pkg\1_0_beta10/init.lua:843>        
        [C]: in function 'xpcall'
        C:/lua/pkg\1_0_beta10/init.lua:923: in function 'require'
        .\test.lua:3: in main chunk
        [C]: at 0x002c1f20
stack traceback:
        [C]: in function 'error'
        C:/lua/pkg\1_0_beta10/init.lua:926: in function 'require'
        .\test.lua:3: in main chunk
        [C]: at 0x002c1f20

How I fix it and install symmath?

**Comment by thenumbernine** [comment]
Read the "Environment / Lua Path" section of the read me and then tell me if you can fix this on your own or not.
