### ISSUE TITLE
How to multiply arrays

### ISSUE THREAD

**Issue by Bissiatti** [thenumbernine/symmath-lua#14]
Hi, How to multiply symmath.arrays? I don't know how I can calcule the scalar product of two vectors and how calcule the cross product in R3?

Thank you very much in advance.

**Comment by thenumbernine** [comment]
For R3 shorthand, there is an Array.cross function:
![image](https://user-images.githubusercontent.com/4241230/161195606-586838dd-b511-4005-bb21-a239c6196082.png)

For higher dimensions there is Tensor.LeviCivita.
![image](https://user-images.githubusercontent.com/4241230/161195715-cc13695e-e50e-4d65-b169-2135bfb5258c.png)

Looks like I still haven't written an Array.dot function -- I probably always only ever used Matrix-multiply for this -- but I can add one easily.
![image](https://user-images.githubusercontent.com/4241230/161195778-7dec7a48-45c3-476c-8d34-e887eb7c5cb7.png)

**Comment by thenumbernine** [comment]
The LeviCivita function can be used as a cross product like so:
![image](https://user-images.githubusercontent.com/4241230/161195933-09356e6f-1fbe-4eb9-95e9-7c3ecaf0c92a.png)

**Comment by thenumbernine** [comment]
If you specify a chart in advance with Tensor.Chart() then Tensor.LeviCivita will use this as the tensor degree:
![image](https://user-images.githubusercontent.com/4241230/161196119-3da1aab1-99ff-4729-9938-80ea70363c97.png)

**Comment by thenumbernine** [comment]
Or you can also cache the component-Tensor of the Levi-Civita, and substitute it into your indexed-tensor expressions:

![image](https://user-images.githubusercontent.com/4241230/161196713-4cca96f8-2e06-460f-a2bc-5b7826489478.png)

**Comment by thenumbernine** [comment]
Alright, the last example can now be done shorthand:
![image](https://user-images.githubusercontent.com/4241230/161202180-3bbb057d-5ca3-4f00-903c-886de040294f.png)
Possibly in the future I will add a `Tensor:permutationSymbol()` like I already have a `Tensor:deltaSymbol()` and `Tensor:metricSymbol()`, and then the `:replace()` from this expression can even be removed.

**Comment by thenumbernine** [comment]
...and I just made that change:
![image](https://user-images.githubusercontent.com/4241230/161212477-f4e421aa-e149-4400-8b62-e6ed598cbc63.png)

**Comment by thenumbernine** [comment]
![image](https://user-images.githubusercontent.com/4241230/161216060-19c92ba3-4017-41d6-9bdd-81800c523031.png)

**Comment by Bissiatti** [comment]
Thank you, I never used a tensor, it's interesting. 

Ok, I understand Array.dot(a,b) is equal to $(a^t \cdot b)$, using matriz, but I know Array.dot(a,b) is more efficient, Array is one-dimensional struct of data.

Anyway, I created the "Array.dot(a,b)" for my use, it's really simple.

**Comment by thenumbernine** [comment]
Ok I added an Array.dot function:
![image](https://user-images.githubusercontent.com/4241230/161410501-831b71bb-9aaa-4b40-be02-cba74bf3bae5.png)

**Comment by thenumbernine** [comment]
But for now it is very limited in function: only multiplying and summing terms of Arrays.  No implications about what it will do for other objects like Matrix or Tensor.

**Comment by Bissiatti** [comment]
Nice. For arrays and matrices is better use matriz Matrix-multiply.
