### ISSUE TITLE
How to install symmath-lua?

### ISSUE THREAD

**Issue by carlosal1015** [thenumbernine/symmath-lua#4]
Hi @thenumbernine, I'm a newcomer in Lua and I do not find the installation guide in in the website of the project. I wish to install symmath-lua in Lua 5.3.

Maybe in the past have planned can use [luarocks](https://luarocks.org/) to host or maybe are in experimental fase.

I'm using Arch Linux distribution.

Thanks in advance.

**Comment by thenumbernine** [comment]
Right now this library only depends on one other, my lua-ext library: https://github.com/thenumbernine/lua-ext

It also requires that you change your LUA_PATH environment variable or your package.path variable to include ?/?.lua, however you can get around this by just moving the ext/ext.lua file to ext.lua and the symmath/symmath.lua to symmath.lua.  Maybe someday I will make a rock out of this and fix this.

**Comment by thenumbernine** [comment]
I added a rockspec to both the ext and symmath projects.  Now you can clone the repos and use 'luarocks install ext-dev-1.rockspec' and then 'luarocks install symmath-dev-1.rockspec'.  Be sure to in that order or else the latter will complain about dependency issues.
